services:
  db:
    image: postgres:14-alpine
    container_name: feedback_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feedback_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - feedback-network

  api:
    build: .
    container_name: feedback_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@db:5432/feedback_db
    networks:
      - feedback-network

networks:
  feedback-network:
    driver: bridge

volumes:
  postgres_data:
